base_image_url: https://pumpons.github.io/sutochno-feeds/images
segments:
- id: sochi-premium
  description: Сочи + Адлер + Красная Поляна с оценкой ≥ 4.5
  filter:
    destination_in:
    - Сочи
    - Адлер
    - Красная Поляна
    min_score: 4.5
  template: premium_gold
  limit: 0
- id: 4-5-stars-pools
  description: Четырех и пятизвездочные отели с бассейнами
  filter:
    min_score: 4.0
    stars_in:
    - 4
    - 5
    amenities_any:
    - Бассейн (открытый)
  template: premium_gold
  limit: 0
- id: ulyanovsk-hotels
  description: Все отели из Ульяновска
  filter:
    destination_in:
    - Ульяновск
  template: premium_gold
  limit: 0
- id: new-segment-4
  description: ''
  filter: {}
  template: premium_gold
  limit: 0
