base_image_url: https://pumpons.github.io/sutochno-feeds/images
segments:
- id: test-jubga-smart-1
  description: джубга тест - 1 шаблон
  filter:
    destination_in:
    - Джубга
    stars_in:
    - 3
    - 4
    - 5
  template: smart_banner_01
  limit: 0
  dedupe_by_url: true
- id: test-jubga-smart-2
  description: ''
  filter:
    destination_in:
    - Джубга
    - Ейск
    stars_in:
    - 1
    - 2
    - 3
    - 4
    - 5
  template: smart_banner_02
  limit: 0
  dedupe_by_url: true
- id: test-jubga-smart-3
  description: ''
  filter:
    destination_in:
    - Джубга
    - Ейск
    stars_in:
    - 1
    - 2
    - 3
    - 4
    - 5
  template: smart_banner_03
  limit: 0
  dedupe_by_url: true
- id: test-jubga-smart-4
  description: ''
  filter:
    destination_in:
    - Джубга
    - Ейск
    stars_in:
    - 1
    - 2
    - 3
    - 4
    - 5
  template: smart_banner_04
  limit: 0
  dedupe_by_url: true
- id: test-jubga-smart-5
  description: ''
  filter:
    destination_in:
    - Джубга
    - Ейск
    stars_in:
    - 1
    - 2
    - 3
    - 4
    - 5
  template: smart_banner_05
  limit: 0
  dedupe_by_url: true
- id: all-hotels-kreo03
  description: ''
  filter: {}
  template: smart_banner_03
  limit: 0
  dedupe_by_url: true
- id: all-hotels-kreo04
  description: ''
  filter: {}
  template: smart_banner_04
  limit: 0
  dedupe_by_url: true
- id: new-segment-8
  description: ''
  filter: {}
  template: premium_gold
  limit: 0
